### PR TITLE
OMS should remember original zIndex of marker

### PR DESCRIPTION
**Pull request by easyest**

### CODE REVIEW

**Comment by andreasderbefreier** [comment]
I just ran into this problem too. This should be committed into the master branch.

**Comment by easyest** [comment]
You can grab my fork of the project as the original is long dead...

**Comment by r0estir0bbe** [comment]
I was going to create a pull request until I saw this one. Merging this into master would be great.

**Comment by GehDoc** [comment]
@jawj : Hi,
can you accept this PR ?

**Comment by jawj** [comment]
I've also made a new JS build, 1.0.2.

**Comment by jawj** [comment]
Closes #117.

**Pull request merged**
